# Configuration for Pressure Relief Valve LLM Agent

# Model Settings
MODEL_NAME: "gpt2"  # Can be changed to other HuggingFace models
EMBEDDINGS_MODEL: "sentence-transformers/all-MiniLM-L6-v2"

# Paths
DATA_DIR: "./data"
UPLOAD_DIR: "./data/uploads"
CACHE_DIR: "./data/cache"
MODELS_DIR: "./models"
VECTORSTORE_DIR: "./data/chroma_db"
LOGS_DIR: "./logs"

# LLM Parameters
MAX_LENGTH: 512
TEMPERATURE: 0.7
TOP_P: 0.9
TOP_K: 50

# Vector Store Settings
CHUNK_SIZE: 1000
CHUNK_OVERLAP: 200
RETRIEVAL_K: 3  # Number of documents to retrieve for each query

# Web Collection Settings
WEB_SEARCH_MAX_RESULTS: 5
WEB_REQUEST_TIMEOUT: 15
WEB_RATE_LIMIT_DELAY: 2  # seconds between requests

# Application Settings
LOG_LEVEL: "INFO"
